# Generated by Django 2.0.7 on 2018-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprojectrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectrequest',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
