# Generated by Django 2.0.7 on 2018-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprojectrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectrequest',
            name='reason',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
