# Generated by Django 2.0.7 on 2018-08-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180806_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectrequest',
            name='reason',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
