# Generated by Django 2.0.7 on 2018-08-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprojectrequest_reason'),
        ('dashboard', '0003_auto_20180806_1217'),
    ]

    operations = [
    ]
