# Generated by Django 2.0.7 on 2018-08-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20180803_0532'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loghours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('hours_logged', models.FloatField(null=True)),
                ('required_hours', models.FloatField(null=True)),
                ('pm_approval', models.BooleanField()),
                ('am_approval', models.BooleanField()),
                ('hourly_rate', models.FloatField(null=True)),
                ('is_valid', models.BooleanField()),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project')),
            ],
        ),
    ]
